In [94]:
#import numpy as np
import sys
l = range(1000)
print(len(l))
print(sys.getsizeof(9)*len(l))
print(l)
array = np.arange(1000)
print(array.size)
print(array.size*array.itemsize)
#print(array.itemsize)

1000
28000
range(0, 1000)
1000
4000


In [97]:
#import numpy as np
#import time

#for list
start = time.time()
size = 10000000
l = range(size )
k = range(size )
sum = [(x+y) for x,y in zip(l,k)]
print(sum[size-1])
print((time.time()-start)*1000)

# for array
start = time.time()
j = np.arange(size )
u = np.arange(size )
sum = j+u
print(sum[size-1])
print((time.time()-start)*1000)


19999998
1732.3672771453857
19999998
278.2564163208008


In [90]:
a = np.array([[1],[2],[4],[5]])
print(np.ndim(a))
print(a.ndim)
print(a*a)
    

2
2
[[ 1]
 [ 4]
 [16]
 [25]]


In [57]:
a.itemsize

4

In [58]:
a.dtype


dtype('int32')

In [61]:
a = np.array([[1],[2],[4],[5]],dtype = np.float64 )
print(a)

[[1.]
 [2.]
 [4.]
 [5.]]


In [62]:
a = np.array([[1],[2],[4],[5]],dtype = np.complex )
print(a)

[[1.+0.j]
 [2.+0.j]
 [4.+0.j]
 [5.+0.j]]


In [63]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [67]:
a = np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [76]:
p =a.ravel()

In [79]:
print(p.shape)
print(p.ndim) 

(1,)
1


In [72]:
a = np.array([[1,2],[6,5]])

In [73]:
a.shape

(2, 2)

In [74]:
a = np.array([1])

In [75]:
a.shape

(1,)

In [100]:
np.linspace(2.0, 7.0, num=5, retstep=True, endpoint = False)

(array([2., 3., 4., 5., 6.]), 1.0)

In [99]:
np.linspace(2.0, 7.0, num=5, retstep=True, endpoint = True)

(array([2.  , 3.25, 4.5 , 5.75, 7.  ]), 1.25)

In [103]:
np.linspace(2.0, 7.0, 5,  endpoint = True, retstep = True)

(array([2.  , 3.25, 4.5 , 5.75, 7.  ]), 1.25)

In [101]:
np.linspace(2,5,3)

array([2. , 3.5, 5. ])

In [104]:
h= np.arange(20)
print(h)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [106]:
h= np.arange(20).reshape(4,5)
print(h)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [108]:
print(h.ravel())
print(h)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [114]:
print(h.min())
print(h.max())

h.sum()

0
19


190

In [122]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]]) 


2

In [123]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x.dot(b)) # for matrix multiplication

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


NameError: name 'b' is not defined

In [131]:
x = np.array([1])
y = np.array([[5,6],[7,8]]) 
print(np.ndim(x))
print(x.shape)
print(y.shape)
print(np.ndim(y))
print(x)
print(y)
print(x+y)
print(x.dot(y)) # matric multiplication not possible


1
(1,)
(2, 2)
2
[1]
[[5 6]
 [7 8]]
[[6 7]
 [8 9]]


ValueError: shapes (1,) and (2,2) not aligned: 1 (dim 0) != 2 (dim 0)

In [8]:
import numpy as np
x = np.arange(20).reshape(4,5)
print(x)
for row in x:
    print(row)
for i in np.ravel(x):
    print(i)
for cell in x.flat:
    print(cell)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


TypeError: 'builtin_function_or_method' object is not iterable

In [10]:
import numpy as np
x = np.arange(20).reshape(4,5)
b = x > 4
print(b)

[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [13]:
print(b.dtype)

bool


In [14]:
print(x[b]) # extracting greater than 4 data from array

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [16]:
x[b]=-1
print(x)

[[ 0  1  2  3  4]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [21]:
import numpy as np
x = np.arange(20).reshape(4,5)
print(x)
b=x==4  # checking which are equal to 4
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[False False False False  True]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [22]:
print(x[b])

[4]


In [26]:
x[b]=0  # substitutes that value which was equal to 4 to 0
print(x)

[[ 0  1  2  3  0]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [14]:
import numpy as np

random = np.random.random((1,5))
print(random)

[[0.21929466 0.88386701 0.90475037 0.67934259 0.02192482]]


In [16]:
import numpy as np

random = np.random.random((2,6))
print(random)

[[0.62365603 0.72003613 0.64981167 0.67891675 0.20934465 0.86269461]
 [0.96789077 0.12794203 0.9969056  0.88910696 0.55311274 0.8895326 ]]


In [20]:
np.reshape(random,(6,2))

array([[0.62365603, 0.72003613],
       [0.64981167, 0.67891675],
       [0.20934465, 0.86269461],
       [0.96789077, 0.12794203],
       [0.9969056 , 0.88910696],
       [0.55311274, 0.8895326 ]])

In [21]:
random.sum()

8.168950551864445

In [23]:
np.sum(random)

8.168950551864445

In [24]:
np.median(random)

0.6994764403261086

In [25]:
np.mod(random)

ValueError: invalid number of arguments

In [33]:
new = np.append(random,0.9969056)
new

array([0.62365603, 0.72003613, 0.64981167, 0.67891675, 0.20934465,
       0.86269461, 0.96789077, 0.12794203, 0.9969056 , 0.88910696,
       0.55311274, 0.8895326 , 0.9969056 ])