In [19]:
import numpy as np

l = np.arange(1,21)
print(l)
l.sum()

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


210

In [20]:
h = l.reshape(4,5)
print(h)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [21]:
print(h.min())
h.max()

1


20

In [28]:
print(l.sum(axis=0)) # axis = 1 is out of bound
print(h.sum())

210
210


In [26]:
k = h.sum(axis = 0)
print(h.sum(axis = 0))
print(k)

[34 38 42 46 50]
[34 38 42 46 50]


In [24]:
print(h.sum(axis = 1))

[15 40 65 90]


In [31]:
print(np.sqrt(h))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]
 [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]
 [4.         4.12310563 4.24264069 4.35889894 4.47213595]]


In [33]:
print(h)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [35]:
print(h.std())
print(np.std(h))

5.766281297335398
5.766281297335398


In [16]:
import numpy as np

x = np.arange(3)
#print(x)
y = np.array([1,2,3])
print(np.hstack((x,y))) # horizontal clubing
print(np.vstack((x,y)))  # vertical clubing

[0 1 2 1 2 3]
[[0 1 2]
 [1 2 3]]


In [7]:
l = np.arange(20).reshape(4,5)
print(l)    

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [8]:
print(np.vsplit(l,2))

[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])]


In [10]:
h = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(h)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(np.vsplit(h,3))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [15]:
print(np.hsplit(h,3))

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [3]:
import numpy as np
x = np.arange(12).reshape(4,3)
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
print(np.vsplit(x,4))



[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [6]:
import numpy as np
x = np.arange(12).reshape(4,3)
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
b = x%2 ==0
print(b)

[[ True False  True]
 [False  True False]
 [ True False  True]
 [False  True False]]


In [8]:
x[b] = 0
print(x)

[[ 0  1  0]
 [ 3  0  5]
 [ 0  7  0]
 [ 9  0 11]]


In [12]:
for cell in x.flat:
    print(cell)

0
1
0
3
0
5
0
7
0
9
0
11


In [10]:
for row in x:
    for cell in row:
        print(cell)

0
1
0
3
0
5
0
7
0
9
0
11


In [13]:
for cell in x.flatten():
    print(cell)

0
1
0
3
0
5
0
7
0
9
0
11


# c order and fortran order

In [18]:
import numpy as np
x = np.arange(12).reshape(4,3)
print(x)
for x in np.nditer(x,order = "C"):  # prints in c order 
    print(x)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [20]:
import numpy as np
x = np.arange(12).reshape(4,3)
print(x)
for x in np.nditer(x,order = "F"):
    print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0
3
6
9
1
4
7
10
2
5
8
11


In [22]:
import numpy as np
x = np.arange(12).reshape(4,3)
print(x)
for c in np.nditer(x,order = "A"):
    print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [23]:
import numpy as np
x = np.arange(12).reshape(4,3)
print(x)
for c in np.nditer(x,order = "K"):
    print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [27]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a):
    print(x, end='  ')

0  1  2  3  4  5  

In [32]:
import numpy as np
x = np.arange(12).reshape(4,3)
print(x)
for c in np.nditer(x,order = "F",flags=['external_loop']):
    print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 3 6 9]
[ 1  4  7 10]
[ 2  5  8 11]


In [39]:
import numpy as np
x = np.arange(12).reshape(4,3)
print(x)
for c in np.nditer(x,op_flags=['readwrite']):  # check https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.nditer.html
    c[...]=c*c
    
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]


In [47]:
import numpy as np

x = np.arange(6).reshape(3,2)
y = np.arange(12,18).reshape(3,2)

print(x)
print(y)

for i,j in np.nditer([x,y]):  # for this, either shape should be same or one of them should be 1
    print(i,j)

[[0 1]
 [2 3]
 [4 5]]
[[12 13]
 [14 15]
 [16 17]]
0 12
1 13
2 14
3 15
4 16
5 17


In [54]:
import numpy as np

x = np.arange(12).reshape(4,3)
y = np.arange(12,16,1).reshape(4,1)

print(x)
print(y)

for i,j in np.nditer([x,y]):  # for this, either shape should be same or one of them should be 1
    print(i,j)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[12]
 [13]
 [14]
 [15]]
0 12
1 12
2 12
3 13
4 13
5 13
6 14
7 14
8 14
9 15
10 15
11 15


In [57]:
import numpy as np

x = np.arange(4).reshape(4,1)
y = np.arange(12,16,1).reshape(4,1)

print(x)
print(y)

for i,j in np.nditer([x,y]):  # for this, either shape should be same or one of them should be 1
    print(i,j)
    print(i+j)

[[0]
 [1]
 [2]
 [3]]
[[12]
 [13]
 [14]
 [15]]
0 12
12
1 13
14
2 14
16
3 15
18
